### ISSUE TITLE
Inconsistency between code and text for PersonRepository

### ISSUE THREAD

**Issue by thbecker** [spring-guides/gs-accessing-data-neo4j#12]
The guide explains that "PersonRepository extends the GraphRepository class [...]". However, the code was changed *) so that org.springframework.data.repository.CrudRepository<Person,String> is extended. (This also isn't in line with other examples found on the net where org.springframework.data.neo4j.repository.CRUDRepository<T> is extended. Is this a problem?)

Either the code or the text of the guide should be adjusted.

*) https://github.com/spring-guides/gs-accessing-data-neo4j/commit/9493ebec7813a6828cf629d9f2025143413e86aa#diff-683c8baed0dcdca4b5cd21f2eb58baa8

**Comment by willis7** [comment]
As above. Please correct this, it is confusing.

**Comment by thomasdarimont** [comment]
Thanks guys!

Cheers,
Thomas
