### ISSUE TITLE
How to unit test this code

### ISSUE THREAD

**Issue by willis7** [spring-guides/gs-accessing-data-neo4j#13]
It would be great to see how we actually test the code we build in this tutorial. I'm not having much luck finding documentation online that doesn't include loads of bootstrapping, which feels like an anti-pattern to the spring boot way.

**Comment by gregturn** [comment]
The question at hand, is does unit testing a Spring Data repository make sense? I could give a detailed answer, but @olivergierke already answered a very similar question revolving around Spring Data JPA, and I feel the concept applies here as well.

http://stackoverflow.com/a/23442457/28214

**Comment by willis7** [comment]
Hi Greg, sorry for the delayed response, I've been on vacation. 

I'm not specifically talking about unit testing, and I would agree with you that integration testing is key in this scenario. I'm making the switch from Grails where this seems to be a fairly simple task and is catered for by the framework - it encourages TDD in my opinion. As per my original post, I cant see any easy way to do this.
