### ISSUE TITLE
Clarify the meaning of Direction.BOTH.

### ISSUE THREAD

**Issue by manonthemat** [spring-guides/gs-accessing-data-neo4j#17]
Clarify the meaning of Direction.BOTH.

> This means that when you generate a TEAMMATE relationship in one direction, it exists in the other direction as well.

This statement contradicts what's actually being written to the graph database.
![screen shot 2016-03-03 at 11 56 26 am](https://cloud.githubusercontent.com/assets/5065940/13507356/17ae3f50-e137-11e5-9c3a-8cc0fa497eff.png)

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-accessing-data-neo4j/commit/785f452bc09c50bb8ef8a559caccb274995dd5b5

**Comment by gregturn** [comment]
And also https://github.com/spring-guides/gs-accessing-data-neo4j/commit/fc653e8a245d8cca057c88038899818fce216052
