### ISSUE TITLE
Documentation and code was not sufficiently updated from copy/paste to function

### ISSUE THREAD

**Issue by clayharris** [spring-guides/gs-accessing-data-neo4j#34]
This example appears to be an incomplete port of a copy-paste from a MySql example.  2 main (semi-breaking) reasons noted:

1. Initial [Start with Spring Initializr](https://github.com/spring-guides/gs-accessing-data-neo4j#starting-with-spring-initializr) instructions list the wrong dependencies.  It specifies JPA and MySQL, but _I think_ it only needs Neo4J, based on the example pom and build.gradle files.

2. Under the [Create a Simple Query](https://github.com/spring-guides/gs-accessing-data-neo4j#create-simple-queries) section, it states that that PersonRepository (which is missing display example) extends GraphRepository.  But it currently does not - it simply extends CrudRepository, which I don't believe is sufficient.  I tried changing it to GraphRepository locally, but it could not find the class.  Should it be Neo4jRepository?

**Comment by Buzzardo** [comment]
I was all set to fix it, only to discover that I had fixed it in subsequent commits. Thanks, though, and sorry about the delay.
